### ISSUE TITLE
Encrypt stream & return stream

### ISSUE THREAD

**Issue by footballs** [calccrypto/Encryptions#6]
Respected @calccrypto ,
Does it supports to **encrypt** **stream**(e.g <**fstream**>) and returns **encrypted** and **seek-able stream** ?
Or is  **possible** to achieve with it ?
Regards.

**Comment by calccrypto** [comment]
There is no streaming mechanism in this library. The closest would be using the modes of operations, for fixed amounts of data. I imagine you can wrap their the encryption algorithm or the modes of operation to accomplish what you want.
