### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by HODAKdev** [calccrypto/Encryptions#7]
![awdwa](https://user-images.githubusercontent.com/82084934/117162807-659dcb00-adc3-11eb-825e-3b446a250779.PNG)
good work!

**Comment by calccrypto** [comment]
Hi. You need to point `GTest_DIR` to a copy of [`googletest`](https://github.com/google/googletest).

**Comment by HODAKdev** [comment]
Works, thanks :)
